### PR TITLE
Add autoconf in README.md to be required on macOS 

### PR DESCRIPTION
**Pull request by KilledByNLP**
Please see #35

### CODE REVIEW

**Comment by nekketsuuu** [comment]
How about add `autoconf` into not only macOS, but also Ubuntu? That is, add `autoconf` to the list of required softwares, and add `autoconf` into the line of `apt-get install`.

**Comment by KilledByNLP** [comment]
Thank you for your kind advice, that's right!
I added it.

**Comment by nekketsuuu** [comment]
@KilledByNLP Could you add `autoconf` on the top of `Prerequisites`' list? Also, how about sorting packages alphabetically (i.e., `brew install autoconf git opam unzip wget`)?

**Comment by KilledByNLP** [comment]
@omasanori @nekketsuuu Thanks! All is done!

**Comment by KilledByNLP** [comment]
@omasanori @gfngfn Conflict is resolved

**Comment by omasanori** [comment]
@gfngfn ping?

**Comment by qnighy** [comment]
The indirect dependency on `conf-autoconf` through `bitv` is now removed by #45. I'm not sure if we still need autoconf.

**Pull request closed without merging**
