### PR TITLE
Add floating-point operations, ceil and floor

### PR DESCRIPTION
**Pull request by elpinal**
This PR adds 2 floating-point operations:

- `ceil : float -> float`
- `floor : float -> float`

### CODE REVIEW

**Comment by nyuichi** [comment]
@elpinal 

Nice pull request 👍 
Could you possibly add some more functions like the following too?

- `truncate : float -> float`
- `round : float -> float`
- `pow : float -> float -> float`      (pow x y = x^y)
- `exp : float -> float`        (exp x = e^x)
- `sqrt : float -> float`
- `log : float -> float -> float`
- `log10 : float -> float`

**Comment by elpinal** [comment]
@nyuichi SATySFi already has a primitive named `round`, with type `float -> int`. SATySFi's `round` is defined as OCaml's `int_of_float`, which in turn is equal to OCaml's `truncate`. What do you think of that?

**Comment by nyuichi** [comment]
@elpinal 

Thanks for your feedback!

> SATySFi already has a primitive named round, with type float -> int.

Aw maybe we need to use a new name other than round. One better name is `float-round`, I think. (cc: @gfngfn)

> SATySFi's round is defined as OCaml's int_of_float, which in turn is equal to OCaml's truncate

What I want is the function called `Float.trunc` in OCaml's standard library, which is not equivalent to `truncate` in Pervasives.
I would name this `float-truncate` following the above convention.
To be honest, their actual names do not matter to me because I will just re-export them in `satysfi-li` as `Float.round` and `Float.truncate`.
So I don't have a strong opinion about this.

**Comment by gfngfn** [comment]
I’m so sorry for the late response… I merged only the implementation of `ceil` and `floor` for now.

Note: currently, `tools/gencode/vminst.ml` is automatically generated from `src/frontend/bytecomp/vminstdef.yaml`. Thus I updated the latter so that it generates the former one, which you had extended. We will probably put only the former under version control in the future.

Thank you for the improvement!

**Pull request merged**
