### PR TITLE
Use opam repo

### LINKED ISSUE #23: Missing dependency of uchar
I noticed that a package [`uchar`](https://opam.ocaml.org/packages/uchar/) is not written in [`opam`](https://github.com/gfngfn/otfm/blob/8f1086ea1773d665cf8e24ecd6c84551e0cc94ed/opam#L16) whereas it's needed for the external package `otfm` ([ref](https://github.com/gfngfn/otfm/blob/8f1086ea1773d665cf8e24ecd6c84551e0cc94ed/opam#L16)). Also, a constraint `"uutf" {>= "1.0.0"}` is missing.

Although `uchar` is unnecessary for OCaml >= 4.03, this should be written in `opam`.
Or, using opam repo (#14) will help.

### PR DESCRIPTION
**Pull request by nekketsuuu**
Implements #14. Also fixes #23.

cc: @nyuichi, if merged, this PR will break the Homebrew formula.

### CODE REVIEW

**Comment by nyuichi** [comment]
@nekketsuuu 

I will fix the formula. BTW, what is the motivation of this pull request?

**Comment by objmagic** [comment]
LGTM!

@nyuichi because using external opam repo is a better solution than git submodules. Current approach of using git submodules looks quite hacky to me...

**Comment by nekketsuuu** [comment]
@nyuichi using the repo simplifies the dependency problem (#23) and the build script of SATySFi itself. Vendoring (i.e., copying libraries under the project root directory) is easy, but sometimes triggers a complex behavior. For example, there may be a conflict if we installed the original version of otfm via OPAM and want to build SATySFi with the vendored version of otfm. So I think only using OPAM is better than making git submodules in order to manage libraries.

**Comment by nyuichi** [comment]
@nekketsuuu 

Thank you for the explanation. That makes sense to me.

**Pull request merged**
