### PR TITLE
bump camel version to >= 4.06.0

### LINKED ISSUE #15: Support OCaml >= 4.06.0

### PR DESCRIPTION
**Pull request by objmagic**
Cannot install with new camel (>= `4.06.0`)

https://github.com/gfngfn/camlpdf/pull/1 should be merged before this PR gets merged.

Resolves #15

### CODE REVIEW

**Comment by objmagic** [comment]
did some other clean-ups. Also, move `core` to the more lightweight `core_kernel`

**Comment by gfngfn** [comment]
I tried to confirm that the code works fine for OCaml 4.06 on macOS 10.12, but failed to install the package `camlimages` 4.2.5 via OPAM. I reported it to the repository of the package \([Issue #22](https://bitbucket.org/camlspotter/camlimages/issues/22/cannot-install-camlimages-425-via-opam-for)\), and `camloeba`-san gave a quick comment that it had been due to a kind of bug that  conditionally happen depending on environments and that `camlimages` 4.2.6 would be released after fixing the bug. Thus I am waiting for the release.

**Comment by objmagic** [comment]
@gfngfn OK. I fixed CI in this PR. So feel free to merge this PR after `camlimages` fix.

**Comment by nekketsuuu** [comment]
@gfngfn It seems that `camlimages.4.2.6` was [merged](https://github.com/ocaml/opam-repository/pull/11399). Could you test this branch again?

**Comment by gfngfn** [comment]
Confirmed that it works fine for OCaml 4.06.0. Thank you. Sorry for the late response due to the sickness.

**Comment by objmagic** [comment]
Please use "squash and merge" button instead of "merge" in the future. "Squash" will squash all my commits in one.

**Pull request merged**
