### PR TITLE
Implements `break-on-regex` and `string-match` primitives

### PR DESCRIPTION
**Pull request by konn**
This pull-request implements `break-on-regex` and `string-match` primitives, which build on top of `Str` package.
These are useful to implement a lightweight syntax highlighting.

### CODE REVIEW

**Comment by qnighy** [comment]
I'm not totally against this PR, but we should at least note that it exposes [regex syntax of `Str`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Str.html). It's fortunate that the syntax is fairly standard and simple, therefore does not prevent portability much.

**Comment by konn** [comment]
@qnighy Exactly. I chose `Str` just because it is a part of standard library and no additional package dependency is required. If we once agree to add good package as a dependency, I will rewrite on it.

**Comment by gfngfn** [comment]
Thank you very much for sending an ambitious PR.

I extended your modification by making a distinction between types `string` and `regexp` for convenience and clarity. The construction of a regular expression from a string can be performed by a newly introduced primitive `regexp-of-string : string -> regexp`. Therefore, the package [Steamer](https://github.com/konn/satysfi-steamer/blob/master/steamer.satyh) of `konn`-san’s own making needs a slight correction in order to keep its functionality.

**Comment by konn** [comment]
Thanks!

**Pull request merged**
