### PR TITLE
Migrate to opam 2.0.

### PR DESCRIPTION
**Pull request by omasanori**
[opam 2.0.0 was released](http://opam.ocaml.org/2.0-preview/blog/opam-2-0-0/)! Now it is time to go forward.

Fixes https://github.com/gfngfn/SATySFi/issues/106

### CODE REVIEW

**Comment by omasanori** [comment]
Oops, I forgot to update README too. Please do not merge until it is fixed.

**Comment by omasanori** [comment]
Note that Homebrew opam formula has not upgraded to 2.0 yet. (Official installation script works as Linux.)

**Comment by nekketsuuu** [comment]
Sounds great! It seems that OPAM2 uses `eval $(opam env)` instead of ``eval `opam config env` `` (See [FAQ](http://opam.ocaml.org/2.0-preview/doc/FAQ.html)). So we should fix instructions in README.md and README-ja.md.

**Comment by omasanori** [comment]
Good catch! I will fix it.

**Pull request merged**
